# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test with various JDK versions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distribution:
          - liberica
          - oracle
        java_version:
          - 8
          - 11
          - 14
          - 17
          - 19
        exclude:
          - distribution: oracle
            java_version: 8
          - distribution: oracle
            java_version: 11
          - distribution: oracle
            java_version: 14

    services:
      monetdb_container:
        image: monetdb/dev-builds:Jun2023
        env:
          MDB_DAEMON_PASS: monetdb
          MDB_DB_ADMIN_PASS: monetdb
        ports:
          - 50000:50000

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: ${{ matrix.distribution }}

    - name: Build
      run: make

    - name: Create jar symlink
      run: ln -s monetdb-jdbc*.jar monetdb-jdbc.jar
      working-directory: jars

    - name: Run JDBC_API_Tester
      run: java -cp jars/monetdb-jdbc.jar:jars/jdbctests.jar JDBC_API_Tester 'jdbc:monetdb://localhost:50000/monetdb?user=monetdb&password=monetdb'

    - name: Run OnClientTester
      run: java -cp jars/monetdb-jdbc.jar:jars/jdbctests.jar OnClientTester 'jdbc:monetdb://localhost:50000/monetdb?user=monetdb&password=monetdb' -v
