# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# or https://github.com/actions/checkout  and  https://github.com/actions/setup-java

name: MacOS

on: [push]

jobs:
  build:

    runs-on: macos-latest

#    services:
#      monetdb_container:
#        image: monetdb/monetdb:latest
#        env:
#          MDB_DAEMON_PASS: monetdb
#          MDB_DB_ADMIN_PASS: monetdb
#        ports:
#          - 50000:50000
# Error: docker: command not found

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 11
        distribution: liberica

    - name: Build
      run: make

    - name: Create jar symlink
      run: ln -s monetdb-jdbc*.jar monetdb-jdbc.jar
      working-directory: jars

# running java test programs fails, due to failed connection. Probably the server was not started. Assistance needed.
#    - name: Run JDBC_API_Tester
#      run: java -cp jars/monetdb-jdbc.jar:jars/jdbctests.jar JDBC_API_Tester 'jdbc:monetdb://localhost:50000/monetdb?user=monetdb&password=monetdb'

#    - name: Run OnClientTester
#      run: java -cp jars/monetdb-jdbc.jar:jars/jdbctests.jar OnClientTester 'jdbc:monetdb://localhost:50000/monetdb?user=monetdb&password=monetdb' -v
