# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# or https://github.com/actions/checkout  and  https://github.com/actions/setup-java

# See https://hub.docker.com/r/monetdb/monetdb/tags for docker image names of official MonetDB releases
# See https://hub.docker.com/r/monetdb/dev-builds/tags for docker image name of default branch

name: Test with various MonetDB versions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        monetdbversion:
          - "monetdb/dev-builds:default"
          - "monetdb/monetdb:latest"
          - "monetdb/monetdb:Mar2025-SP2"
          - "monetdb/monetdb:Mar2025-SP1"
          - "monetdb/monetdb:Mar2025"
          - "monetdb/monetdb:Aug2024-SP2"
          - "monetdb/monetdb:Dec2023-SP4"
          - "monetdb/monetdb:Jun2023-SP3"
          - "monetdb/monetdb:Sep2022-SP3"
          - "monetdb/monetdb:Jan2022-SP4"
          - "monetdb/monetdb:Jul2021-SP2"

    services:
      monetdb_container:
        image: ${{ matrix.monetdbversion }}
        env:
          MDB_DAEMON_PASS: monetdb
          MDB_DB_ADMIN_PASS: monetdb
        ports:
          - 50000:50000

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: liberica

    - name: Build
      run: make

    - name: Create jar symlinks
      run: |
        ln -sv monetdb-jdbc-*.jre*.jar monetdb-jdbc.jar
        ln -sv merocontrol.*.jar merocontrol.jar
      working-directory: jars

    - name: Run JDBC_API_Tester
      run: java -cp jars/monetdb-jdbc.jar:jars/jdbctests.jar JDBC_API_Tester 'jdbc:monetdb://localhost:50000/monetdb?user=monetdb&password=monetdb'

    - name: Run OnClientTester
      run: java -cp jars/monetdb-jdbc.jar:jars/jdbctests.jar OnClientTester 'jdbc:monetdb://localhost:50000/monetdb?user=monetdb&password=monetdb' -v

    - name: Run ControlTester
      run: java -cp jars/monetdb-jdbc.jar:jars/merocontrol.jar:jars/jdbctests.jar ControlTester localhost monetdb
